"""change Sale.timestamp to store an ISO date instead

Revision ID: 0b5c26de12e8
Revises: f05141452240
Create Date: 2025-06-19 16:53:06.112972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b5c26de12e8'
down_revision: Union[str, None] = 'f05141452240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'timestamp',
               existing_type=sa.String(length=32),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
