"""points_price

Revision ID: 26ed8b58ed4c
Revises: ae7db22eebe1
Create Date: 2025-10-09 16:56:56.557715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26ed8b58ed4c"
down_revision: Union[str, None] = "ae7db22eebe1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("points_price", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "points_price")
    # ### end Alembic commands ###
