"""descuentos/puntos y reseñas

Revision ID: 39cd2abfe91c
Revises: 86e208ecdd10
Create Date: 2025-10-24 14:02:28.093894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "39cd2abfe91c"
down_revision: Union[str, None] = "86e208ecdd10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("discounts", sa.Column("min_amount", sa.Integer(), nullable=False))
    op.add_column("discounts", sa.Column("max_amount", sa.Integer(), nullable=False))
    op.drop_column("discounts", "type")
    op.drop_column("discounts", "condition")
    op.drop_column("points", "max")
    op.add_column("products", sa.Column("points_price", sa.Integer(), nullable=True))
    op.add_column("stores", sa.Column("ps_value", sa.Integer(), nullable=True))
    op.drop_column("stores", "ps_enabled")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stores",
        sa.Column("ps_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("stores", "ps_value")
    op.drop_column("products", "points_price")
    op.add_column(
        "points", sa.Column("max", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "discounts",
        sa.Column(
            "condition",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "discounts",
        sa.Column("type", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("discounts", "max_amount")
    op.drop_column("discounts", "min_amount")
    # ### end Alembic commands ###
