"""verification code type enum para no tener que reescribir todo

Revision ID: 4647682b7ea8
Revises: 6fcb092f1a5f
Create Date: 2025-10-29 18:50:10.629918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4647682b7ea8"
down_revision: Union[str, None] = "6fcb092f1a5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_verification_codes",
        sa.Column(
            "type",
            sa.Enum(
                "EMAIL",
                "STORE_ADD",
                "PASSWORD_RESET",
                name="verification_code_type_enum",
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "users", sa.Column("cashier_pending_code", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "cashier_pending_code")
    op.drop_column("email_verification_codes", "type")
    # ### end Alembic commands ###
