"""empty message

Revision ID: 53329e68f972
Revises: 4647682b7ea8
Create Date: 2025-10-29 18:54:21.213728

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53329e68f972"
down_revision: Union[str, None] = "4647682b7ea8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE verification_code_type_enum AS ENUM ('EMAIL', 'STORE_ADD', 'PASSWORD_RESET')"
    )
    op.add_column(
        "email_verification_codes",
        sa.Column(
            "type",
            sa.Enum(
                "EMAIL",
                "STORE_ADD",
                "PASSWORD_RESET",
                name="verification_code_type_enum",
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_verification_codes", "type")
    op.execute("DROP TYPE verification_code_type_enum")
    # ### end Alembic commands ###
