"""teibolera

Revision ID: 649d1693dd6a
Revises: 8e12bdd70024
Create Date: 2025-10-29 23:12:56.319772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "649d1693dd6a"
down_revision: Union[str, None] = "8e12bdd70024"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE store_role_enum RENAME VALUE 'cashier-pending' TO 'cashier_pending'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE store_role_enum RENAME VALUE 'cashier_pending' TO 'cashier-pending'"
    )
    # ### end Alembic commands ###
