"""Make User.store_role nullable

Revision ID: 691e74c087d9
Revises: a4c394c9f0a8
Create Date: 2025-07-03 17:27:20.250265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '691e74c087d9'
down_revision: Union[str, None] = 'a4c394c9f0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'store_role',
               existing_type=postgresql.ENUM('CASHIER', 'OWNER', name='store_role_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'store_role',
               existing_type=postgresql.ENUM('CASHIER', 'OWNER', name='store_role_enum'),
               nullable=False)
    # ### end Alembic commands ###
