"""Fix Sale.payment_method spelling

Revision ID: 7b82e3aa406a
Revises: 821b4a93f758
Create Date: 2025-06-19 10:22:34.382133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b82e3aa406a'
down_revision: Union[str, None] = '821b4a93f758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('payment_method', sa.Integer(), nullable=False))
    op.drop_column('sales', 'payement_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('payement_method', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('sales', 'payment_method')
    # ### end Alembic commands ###
