"""Fix product fields

Revision ID: 821b4a93f758
Revises: 97bf9e43372a
Create Date: 2025-06-19 10:00:18.776739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "821b4a93f758"
down_revision: Union[str, None] = "97bf9e43372a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("barcode", sa.String(), nullable=True))
    op.alter_column(
        "products",
        "quantity",
        existing_type=sa.INTEGER(),
        type_=sa.DOUBLE_PRECISION(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "quantity",
        existing_type=sa.DOUBLE_PRECISION(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("products", "barcode")
    # ### end Alembic commands ###
