"""ps_max

Revision ID: 86e208ecdd10
Revises: 26ed8b58ed4c
Create Date: 2025-10-11 01:33:22.772908

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86e208ecdd10"
down_revision: Union[str, None] = "26ed8b58ed4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "ps_max")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stores", sa.Column("ps_max", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
