"""fix orders.qty type

Revision ID: 8c4083d52110
Revises: 252eac14abe7
Create Date: 2025-09-20 19:37:40.674582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c4083d52110"
down_revision: Union[str, None] = "252eac14abe7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders_products",
        "quantity",
        existing_type=sa.INTEGER(),
        type_=sa.DOUBLE_PRECISION(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders_products",
        "quantity",
        existing_type=sa.DOUBLE_PRECISION(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
