"""temporarily make Store.category nullable

Revision ID: 963dc95644f9
Revises: 7da6a0847371
Create Date: 2025-07-01 14:03:57.014073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "963dc95644f9"
down_revision: Union[str, None] = "7da6a0847371"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stores", sa.Column("category", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "category")
    # ### end Alembic commands ###
