"""recievevefedd

Revision ID: 98ac0210479f
Revises: a49dac8c68da
Create Date: 2025-08-26 13:42:07.317234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "98ac0210479f"
down_revision: Union[str, None] = "a49dac8c68da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("received_at", postgresql.TIME(timezone=True), nullable=True),
    )
    op.add_column("orders", sa.Column("payment_method", sa.Integer(), nullable=False))
    op.drop_column("orders", "payement_method")
    op.drop_column("orders", "recieved_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "recieved_at",
            postgresql.TIME(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "orders",
        sa.Column("payement_method", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("orders", "payment_method")
    op.drop_column("orders", "received_at")
    # ### end Alembic commands ###
