"""arreglar cosas raras de puntos

Revision ID: 9ae352afb078
Revises: 0ffd7032c8d5
Create Date: 2025-09-25 10:07:12.509968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ae352afb078"
down_revision: Union[str, None] = "0ffd7032c8d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("points", "max")
    op.add_column("stores", sa.Column("ps_max", sa.Integer(), nullable=True))
    op.add_column("stores", sa.Column("ps_value", sa.Integer(), nullable=True))
    op.drop_column("stores", "ps_enabled")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stores",
        sa.Column("ps_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("stores", "ps_value")
    op.drop_column("stores", "ps_max")
    op.add_column(
        "points", sa.Column("max", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
