"""arreglar received por vez 1000

Revision ID: a49dac8c68da
Revises: f02bcc8209e0
Create Date: 2025-08-07 10:39:34.472571

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a49dac8c68da"
down_revision: Union[str, None] = "f02bcc8209e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("received_at", postgresql.TIME(timezone=True), nullable=True),
    )
    op.drop_column("orders", "recieved_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "recieved_at",
            postgresql.TIME(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("orders", "received_at")
    # ### end Alembic commands ###
