"""and make it nullable again

Revision ID: a4c394c9f0a8
Revises: ff90662a50a5
Create Date: 2025-07-01 14:08:02.711078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c394c9f0a8'
down_revision: Union[str, None] = 'ff90662a50a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'category',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'category',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
