"""Cambiar nullable

Revision ID: ad41c827ce7e
Revises: e16956d5ec80
Create Date: 2025-08-07 09:56:46.666520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad41c827ce7e'
down_revision: Union[str, None] = 'e16956d5ec80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'recieved_at',
               existing_type=postgresql.TIME(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'recieved_at',
               existing_type=postgresql.TIME(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
