"""rm Discount.type

Revision ID: ae7db22eebe1
Revises: d1224a08ef31
Create Date: 2025-09-29 08:40:45.545457

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae7db22eebe1"
down_revision: Union[str, None] = "d1224a08ef31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("discounts", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "discounts",
        sa.Column("type", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
