"""Fix numbers/fields in Sale and Store

Revision ID: b1556e6ff3dd
Revises: 691e74c087d9
Create Date: 2025-07-08 22:14:25.449963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1556e6ff3dd'
down_revision: Union[str, None] = '691e74c087d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'days_open')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('days_open', postgresql.ARRAY(sa.BOOLEAN()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
