"""hola mundo

Revision ID: d1224a08ef31
Revises: f4a9a249c418
Create Date: 2025-09-25 11:48:51.951378

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d1224a08ef31"
down_revision: Union[str, None] = "f4a9a249c418"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("discounts", sa.Column("min_amount", sa.Integer(), nullable=False))
    op.add_column("discounts", sa.Column("max_amount", sa.Integer(), nullable=False))
    op.drop_column("discounts", "condition")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "discounts",
        sa.Column(
            "condition",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("discounts", "max_amount")
    op.drop_column("discounts", "min_amount")
    # ### end Alembic commands ###
