"""Store category

Revision ID: ddf779a9c51a
Revises: fb79f4687861
Create Date: 2025-06-26 17:25:37.521229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ddf779a9c51a"
down_revision: Union[str, None] = "fb79f4687861"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stores", sa.Column("category", sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "category")
    # ### end Alembic commands ###
