"""agregar Product.hidden

Revision ID: e16956d5ec80
Revises: f92dfd286740
Create Date: 2025-07-17 10:20:16.381244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16956d5ec80'
down_revision: Union[str, None] = 'f92dfd286740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
