"""fix descuentos

Revision ID: e2afe13c706f
Revises: f9fcd3821b46
Create Date: 2025-09-25 10:37:25.218322

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e2afe13c706f"
down_revision: Union[str, None] = "f9fcd3821b46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("discounts", sa.Column("min_amount", sa.Integer(), nullable=False))
    op.add_column("discounts", sa.Column("max_amount", sa.Integer(), nullable=False))
    op.drop_column("discounts", "condition")
    op.add_column("points", sa.Column("max", sa.Integer(), nullable=False))
    op.add_column("stores", sa.Column("ps_enabled", sa.Boolean(), nullable=False))
    op.drop_column("stores", "ps_max")
    op.drop_column("stores", "ps_value")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stores",
        sa.Column("ps_value", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "stores", sa.Column("ps_max", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_column("stores", "ps_enabled")
    op.drop_column("points", "max")
    op.add_column(
        "discounts",
        sa.Column(
            "condition",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("discounts", "max_amount")
    op.drop_column("discounts", "min_amount")
    # ### end Alembic commands ###
