"""merge?

Revision ID: e3ff50266e5a
Revises: ab85c4e4a6e8
Create Date: 2025-09-21 02:11:59.460168

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3ff50266e5a"
down_revision: Union[str, None] = "ab85c4e4a6e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders_products",
        "quantity",
        existing_type=sa.INTEGER(),
        type_=sa.DOUBLE_PRECISION(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders_products",
        "quantity",
        existing_type=sa.DOUBLE_PRECISION(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
