"""arreglar payement por vez 1000

Revision ID: f02bcc8209e0
Revises: ad41c827ce7e
Create Date: 2025-08-07 10:30:14.722423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f02bcc8209e0"
down_revision: Union[str, None] = "ad41c827ce7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("payment_method", sa.Integer(), nullable=False))
    op.drop_column("orders", "payement_method")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("payement_method", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("orders", "payment_method")
    # ### end Alembic commands ###
