"""fix Sale.timestamp type

Revision ID: f081a37e8855
Revises: a9bb7d5245d9
Create Date: 2025-06-19 11:29:35.475238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f081a37e8855'
down_revision: Union[str, None] = 'a9bb7d5245d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'timestamp',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
