"""latlng, pt. 1

Revision ID: f21fe1b58feb
Revises: 05022780ab7c
Create Date: 2025-11-11 13:51:25.776316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f21fe1b58feb"
down_revision: Union[str, None] = "05022780ab7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stores", sa.Column("latitude", sa.Double(), nullable=True))
    op.add_column("stores", sa.Column("longitude", sa.Double(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "longitude")
    op.drop_column("stores", "latitude")
    # ### end Alembic commands ###
