"""Make Sale.user_id nullable

Revision ID: f92dfd286740
Revises: b1556e6ff3dd
Create Date: 2025-07-16 14:05:34.899489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92dfd286740'
down_revision: Union[str, None] = 'b1556e6ff3dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
