"""change products qty type

Revision ID: fb79f4687861
Revises: 0b5c26de12e8
Create Date: 2025-06-19 17:23:22.297814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb79f4687861'
down_revision: Union[str, None] = '0b5c26de12e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products_sales', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.DOUBLE_PRECISION(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products_sales', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
